# Site settings
title: FAM Rashel
header-img: img/home-bg.jpg
email: 1234@yahoo.com
copyright_name: FAM
description: "Projects, travels, musics, anything else"
baseurl: "famrashel.github.io"
url: "http://famrashel.github.io"
twitter_username: famrashel
github_username:  famrashel
facebook_username:  fam.rashel.scala
email_username:  1234@yahoo.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
# permalink: pretty
paginate: 5
paginate_path: "/news/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

# Collections
collections:
  projects:
    output: true

